# Generated by Django 3.0.7 on 2020-07-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200705_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.AuctionListing'),
        ),
    ]
