# Generated by Django 3.0.7 on 2020-07-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200705_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(),
        ),
    ]
