# Generated by Django 3.0.7 on 2020-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200705_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(to='auctions.AuctionListing'),
        ),
    ]
