# Generated by Django 3.0.8 on 2020-07-05 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200705_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
